nome = str(input('Digite seu nome completo: '))
print('Analisando seu nome...')
print('Seu nome em maiuscula é {}'.format(nome.upper()))
print(nome.lower())
print(len(nome) - nome.count(' '))
print(nome.find(' '))